// <auto-generated />
using Barker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240611124116_minitestdown")]
    partial class minitestdown
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Barker.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Вершина якості",
                            Img = "/img/category_img/barker_cat_anniv.jpg",
                            Name = "anniversary"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ручна робота",
                            Img = "/img/category_img/barker_cat_handc.jpg",
                            Name = "handcrafted"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Потовщена підошва",
                            Img = "/img/category_img/barker_cat_country.jpg",
                            Name = "country"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Сучасний дизайн",
                            Img = "/img/category_img/barker_cat_creative.jpg",
                            Name = "creative"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Гнучкі та легкі",
                            Img = "/img/category_img/barker_cat_flex.jpg",
                            Name = "barkerflex"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Класика поза часом",
                            Img = "/img/category_img/barker_cat_prof.jpg",
                            Name = "professional"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Винятковий комфорт",
                            Img = "/img/category_img/mocc-category_2.jpg",
                            Name = "moccasin"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Стильні та якісні аксесуари",
                            Img = "/img/category_img/accesory_cat.jpg",
                            Name = "accessory"
                        });
                });

            modelBuilder.Entity("Barker.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Shoe")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoleMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VendorCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Availability = true,
                            CategoryId = 1,
                            Color = "чорний",
                            Country = "Англія",
                            Description = "Класичні оксфорди з натуральної шкіри, ручної роботи.",
                            Fullness = "G",
                            Img = "[\"/img/product_Img/Lerwick-431527_AntiqueRosewood_1080x.png\",\"/img/product_img/Lerwick_431527_AntiqueRosewoodCalf_side_1024x6002x.png\",\"/img/product_img/Lerwick_431527_AntiqueRosewood_top_1024x6002x.png\",\"/img/product_img/Rochester_380417_7mm_Leather_464Last_1024x6002x.png\"]",
                            Name = "LERWICK ANTIQUE ROSEWOOD",
                            Shoe = 464,
                            Size = "[6,8.5,9]",
                            Sole = "шкіра",
                            SoleMethod = "рантовий",
                            Style = "оксфорд",
                            TopMaterial = "Натуральна шкіра",
                            VendorCode = 431527
                        });
                });

            modelBuilder.Entity("Barker.Models.ProductModel", b =>
                {
                    b.HasOne("Barker.Models.CategoryModel", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Barker.Models.CategoryModel", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
