// <auto-generated />
using Barker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Barker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240610101915_AddCategoryModels")]
    partial class AddCategoryModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Barker.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Вершина якості",
                            Img = "/img/category_img/barker_cat_anniv.jpg",
                            Name = "Anniversary"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ручна робота",
                            Img = "/img/category_img/barker_cat_handc.jpg",
                            Name = "Handcrafted"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Потовщена підошва",
                            Img = "/img/category_img/barker_cat_country.jpg",
                            Name = "Country"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Сучасний дизайн",
                            Img = "/img/category_img/barker_cat_creative.jpg",
                            Name = "Creative"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Гнучкі та легкі",
                            Img = "/img/category_img/barker_cat_flex.jpg",
                            Name = "Barkerflex"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Класика поза часом",
                            Img = "/img/category_img/barker_cat_prof.jpg",
                            Name = "Professional"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Винятковий комфорт",
                            Img = "/img/category_img/mocc-category_2.jpg",
                            Name = "Moccasin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
